In [1]:
import numpy  as np
# import pandas as pd -- tomorrow

### Create an array from an iterable
Such as
- ```list```
- ```tuple```
- ```range``` iterator

Notice that not all iterables can be used to create a numpy array, such as ```set``` and ```dict```

In [5]:
arr = np.array([1,2,3,4,5])
print(arr)
# [] - list

[1 2 3 4 5]


In [6]:
type(arr)

numpy.ndarray

In [7]:
arr = np.array((1,2,3,4,5))
print(arr)
# () = tuple

[1 2 3 4 5]


In [8]:
type(arr)

numpy.ndarray

In [9]:
arr = np.array(range(2,10))
print(arr)

[2 3 4 5 6 7 8 9]


In [10]:
arr = np.array(range(10))
print(arr)

[0 1 2 3 4 5 6 7 8 9]


### Create an array with specified data type

In [17]:
arr1 = np.array(range(10))
print(arr1)

[0 1 2 3 4 5 6 7 8 9]


In [18]:
arr1.ndim

1

In [19]:
arr = np.array([[1,2,3], [4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [20]:
arr.ndim

2

In [21]:
ar = np.array([[[1,2,3]]])
print(ar)

[[[1 2 3]]]


In [22]:
ar.ndim

3

### Create an aray within specified range
```np.arange()``` method can be used to replace ```np.array(range())``` method

In [ ]:
# range(0,10) --> [0....9]
# range(3,6)  --> [3,4,5]

In [23]:
# np.arange(start, stop, step)
arr = np.arange(0,20,2)
print(arr)

[ 0  2  4  6  8 10 12 14 16 18]


In [24]:
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

### Create an array of evenly spaced numbers within specified range


In [36]:
# start-0, end-20, elements-5
np.linspace(0,20,5)

array([ 0.,  5., 10., 15., 20.])

In [37]:
# start-0, end-20, elements-5
np.linspace(0,20,5, endpoint=False)

array([ 0.,  4.,  8., 12., 16.])

In [44]:
np.linspace(0,20,7,endpoint=True)

array([ 0.        ,  3.33333333,  6.66666667, 10.        , 13.33333333,
       16.66666667, 20.        ])

In [45]:
np.linspace(0,20,7,endpoint=False)

array([ 0.        ,  2.85714286,  5.71428571,  8.57142857, 11.42857143,
       14.28571429, 17.14285714])